/*
 * Copyright (c) Nmote d.o.o. 2003-2015. All rights reserved.
 * See LICENSE.txt for licensing information.
 */

/*
 * WARNING Do not modify this file.
 *
 * This file was generated from protocol description file
 * and will be OVERWRITTEN on next invocation of
 * smpp-gen ant task during build process.
 */

package com.nmote.smpp;

/**
 * Utility class containing constants specifying PDU command IDs.
 *
 * @author (this class was autogenerated)
 */
public class PDU {
    public static final int OUTBIND = 11;
    public static final int BIND_TRANSMITTER = 2;
    public static final int REPLACE_SM = -2147483641;
    public static final int QUERY_BROADCAST_SM = 274;
    public static final int SUBMIT_MULTI = 33;
    public static final int QUERY_SM = 3;
    public static final int ENQUIRE_LINK_RESP = -2147483627;
    public static final int DELIVER_SM = 5;
    public static final int BROADCAST_SM_RESP = -2147483375;
    public static final int DATA_SM = 259;
    public static final int BIND_TRANSMITTER_RESP = -2147483646;
    public static final int QUERY_BROADCAST_SM_RESP = -2147483374;
    public static final int GENERIC_NACK = -2147483648;
    public static final int DELIVER_SM_RESP = -2147483643;
    public static final int CANCEL_SM = 8;
    public static final int BIND_RECEIVER = 1;
    public static final int SUBMIT_SM_RESP = -2147483644;
    public static final int SUBMIT_MULTI_RESP = -2147483615;
    public static final int QUERY_SM_RESP = -2147483645;
    public static final int ALERT_NOTIFICATION = 258;
    public static final int CANCEL_SM_RESP = -2147483640;
    public static final int BIND_RECEIVER_RESP = -2147483647;
    public static final int SUBMIT_SM = 4;
    public static final int CANCEL_BROADCAST_SM_RESP = -2147483373;
    public static final int DATA_SM_RESP = -2147483389;
    public static final int UNBIND = 6;
    public static final int BROADCAST_SM = 273;
    public static final int BIND_TRANSCEIVER = 9;
    public static final int BIND_TRANSCEIVER_RESP = -2147483639;
    public static final int UNBIND_RESP = -2147483642;
    public static final int CANCEL_BROADCAST_SM = 275;
    public static final int ENQUIRE_LINK = 21;
    public static final int REPLACE_SM_RESP = 7;

	/**
	 * Converts command id <code>cid</code> into a
	 * String representation.
	 *
	 * @param cid SMPP Command ID
	 * @return String representation
	 */
	public static String toString(int cid) {
		String result;
		switch (cid) {
			case OUTBIND: result = "outbind"; break;
			case BIND_TRANSMITTER: result = "bind_transmitter"; break;
			case REPLACE_SM: result = "replace_sm"; break;
			case QUERY_BROADCAST_SM: result = "query_broadcast_sm"; break;
			case SUBMIT_MULTI: result = "submit_multi"; break;
			case QUERY_SM: result = "query_sm"; break;
			case ENQUIRE_LINK_RESP: result = "enquire_link_resp"; break;
			case DELIVER_SM: result = "deliver_sm"; break;
			case BROADCAST_SM_RESP: result = "broadcast_sm_resp"; break;
			case DATA_SM: result = "data_sm"; break;
			case BIND_TRANSMITTER_RESP: result = "bind_transmitter_resp"; break;
			case QUERY_BROADCAST_SM_RESP: result = "query_broadcast_sm_resp"; break;
			case GENERIC_NACK: result = "generic_nack"; break;
			case DELIVER_SM_RESP: result = "deliver_sm_resp"; break;
			case CANCEL_SM: result = "cancel_sm"; break;
			case BIND_RECEIVER: result = "bind_receiver"; break;
			case SUBMIT_SM_RESP: result = "submit_sm_resp"; break;
			case SUBMIT_MULTI_RESP: result = "submit_multi_resp"; break;
			case QUERY_SM_RESP: result = "query_sm_resp"; break;
			case ALERT_NOTIFICATION: result = "alert_notification"; break;
			case CANCEL_SM_RESP: result = "cancel_sm_resp"; break;
			case BIND_RECEIVER_RESP: result = "bind_receiver_resp"; break;
			case SUBMIT_SM: result = "submit_sm"; break;
			case CANCEL_BROADCAST_SM_RESP: result = "cancel_broadcast_sm_resp"; break;
			case DATA_SM_RESP: result = "data_sm_resp"; break;
			case UNBIND: result = "unbind"; break;
			case BROADCAST_SM: result = "broadcast_sm"; break;
			case BIND_TRANSCEIVER: result = "bind_transceiver"; break;
			case BIND_TRANSCEIVER_RESP: result = "bind_transceiver_resp"; break;
			case UNBIND_RESP: result = "unbind_resp"; break;
			case CANCEL_BROADCAST_SM: result = "cancel_broadcast_sm"; break;
			case ENQUIRE_LINK: result = "enquire_link"; break;
			case REPLACE_SM_RESP: result = "replace_sm_resp"; break;
			default: result = "unknown(" + Integer.toHexString(cid) + ")";
		}
		return result;
	}

    /**
     * Array with all supported PDU command ids.
     * <i>Warning: This array is used only for unit testing and
     * it is not a public API</i>
     */
	public static final int[] _ALL_COMMAND_IDS = {
		OUTBIND,
		BIND_TRANSMITTER,
		REPLACE_SM,
		QUERY_BROADCAST_SM,
		SUBMIT_MULTI,
		QUERY_SM,
		ENQUIRE_LINK_RESP,
		DELIVER_SM,
		BROADCAST_SM_RESP,
		DATA_SM,
		BIND_TRANSMITTER_RESP,
		QUERY_BROADCAST_SM_RESP,
		GENERIC_NACK,
		DELIVER_SM_RESP,
		CANCEL_SM,
		BIND_RECEIVER,
		SUBMIT_SM_RESP,
		SUBMIT_MULTI_RESP,
		QUERY_SM_RESP,
		ALERT_NOTIFICATION,
		CANCEL_SM_RESP,
		BIND_RECEIVER_RESP,
		SUBMIT_SM,
		CANCEL_BROADCAST_SM_RESP,
		DATA_SM_RESP,
		UNBIND,
		BROADCAST_SM,
		BIND_TRANSCEIVER,
		BIND_TRANSCEIVER_RESP,
		UNBIND_RESP,
		CANCEL_BROADCAST_SM,
		ENQUIRE_LINK,
		REPLACE_SM_RESP,
	};
}