/*
 * Copyright (c) Nmote d.o.o. 2003-2015. All rights reserved.
 * See LICENSE.txt for licensing information.
 */

/*
 * WARNING Do not modify this file.
 *
 * This file was generated from protocol description file
 * and will be OVERWRITTEN on next invocation of
 * smpp-gen ant task during build process.
 */

package com.nmote.smpp;

import java.io.IOException;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;

/**
 * The replace_sm PDU is used by an ESME to pass a
message_id of a previously submitted message along with
several other fields used to update the text, validity period
and other attributes of the message.
  
 *
 * @author (this class was autogenerated)
 */
public class ReplaceSmPDU extends AbstractPDU {

    private static final long serialVersionUID = About.SERIAL_VERSION_UID;

    /**
     * Creates a new PDU object.
     */
    public ReplaceSmPDU() {
    }

    /**
     * Returns Command ID for this PDU.
     *
     * @return PDU.REPLACE_SM;
     */
    public int getCommandId() {
        return PDU.REPLACE_SM;
    }

    /**
     * Reads mandatory and optional parameters from SMPPInputStream.
     *
     * @param in SMPPInputStream for reading parameters.
     * @throws IOException In case of a problem while reading data.
     */
    void readParameters(SMPPInputStream in) throws IOException {
		// Mandatory parameters
		message_id = in.readCString();
		source_addr = in.readSMPPAddress();
		schedule_delivery_time = in.readSMPPTime();
		validity_period = in.readSMPPTime();
		registered_delivery = in.readInteger1();
		sm_default_msg_id = in.readInteger1();
		short_message = in.readPString();

		// Optional parameters
		readOptionalParameters(in);
    }

    /**
     * Write mandatory and optional PDU parameters to SMPPOutputStream.
     *
     * @param out SMPPOutputStream for writting paramters.
     * @throws IOException In case of errors while writing.
     */
    void writeParameters(SMPPOutputStream out) throws IOException {
        // Mandatory parameters
		out.writeCString(message_id);
		out.writeSMPPAddress(source_addr);
		out.writeSMPPTime(schedule_delivery_time);
		out.writeSMPPTime(validity_period);
		out.writeInteger1(registered_delivery);
		out.writeInteger1(sm_default_msg_id);
		out.writePString(short_message);

		// Optional parameters
		writeOptionalParameters(out);
    }

    /**
     * @see com.nmote.smpp.AbstractPDU#isRequestPDU()
     */
	public boolean isRequestPDU() {
		return false;
	}

	/**
	 * @see com.nmote.smpp.AbstractPDU#createResponse()
	 */
	public AbstractPDU createResponse() {
		throw new UnsupportedOperationException();
	}

	/**
	 * @see com.nmote.smpp.AbstractPDU#isOneWay()
	 */
	public final boolean isOneWay() {
		return false;
	}

    /**
     * Returns PDU name.
     *
     * @return PDU name
     */
    public String getName() {
    	return "replace_sm";
    }

    /**
     * Creates a string representation of a PDU.
     *
     * @return a String
     */
    public String toString() {
    	ToStringBuilder b = new ToStringBuilder(this);
    	b.append(getSequence());
    	b.append(ESMEStatus.toString(getStatus()));

        // Appending mandatory parameters
        b.append("message_id", toStringHelper(message_id));
        b.append("source_addr", toStringHelper(source_addr));
        b.append("schedule_delivery_time", toStringHelper(schedule_delivery_time));
        b.append("validity_period", toStringHelper(validity_period));
        b.append("registered_delivery", toStringHelper(registered_delivery));
        b.append("sm_default_msg_id", toStringHelper(sm_default_msg_id));
        b.append("short_message", toStringHelper(short_message));

        // Appending optional parameters
        if (getParameters() != null) {
        	b.append(getParameters());
        }

        return b.toString();
    }

    /**
     * Calculates hash code of this object.
     *
     * @return hash code
     */
    public int hashCode() {
    	HashCodeBuilder b = new HashCodeBuilder();
    	b.append(getSequence());
    	b.append(getStatus());

        // Appending mandatory parameters
        b.append(message_id);
        b.append(source_addr);
        b.append(schedule_delivery_time);
        b.append(validity_period);
        b.append(registered_delivery);
        b.append(sm_default_msg_id);
        b.append(short_message);

        // Appending optional parameters
        if (getParameters() != null) {
        	b.append(getParameters());
        }

        return b.toHashCode();
    }

    /**
     * Checks if <code>o</code> and this object are equal.
     *
     * @return true if objects are equal, false otherwise
     */
    public boolean equals(Object o) {
    	boolean result;
    	if (o instanceof ReplaceSmPDU) {
    		ReplaceSmPDU p = (ReplaceSmPDU) o;
    		EqualsBuilder b = new EqualsBuilder();
	    	b.append(p.getSequence(), getSequence());
    		b.append(p.getStatus(), getStatus());

	        // Appending mandatory parameters
    	    b.append(p.message_id, message_id);
    	    b.append(p.source_addr, source_addr);
    	    b.append(p.schedule_delivery_time, schedule_delivery_time);
    	    b.append(p.validity_period, validity_period);
    	    b.append(p.registered_delivery, registered_delivery);
    	    b.append(p.sm_default_msg_id, sm_default_msg_id);
    	    b.append(p.short_message, short_message);

	        // Appending optional parameters
        	b.append(p.getParameters(), getParameters());

        	result = b.isEquals();
        } else {
        	result = false;
        }

        return result;
    }

    // Mandatory parameters

    private String message_id;

    /**
     * Getter for a mandatory parameter message_id.
     * The unique message identifier reference assigned by the MC to each submitted short message. It is an opaque value and is set according to MC implementation.
     * @return parameter value
     */
    public String getMessageId() {
		return message_id;
    }

    /**
     * Setter for a mandatory parameter message_id.
     * The unique message identifier reference assigned by the MC to each submitted short message. It is an opaque value and is set according to MC implementation.
     * @param value New parameter value.
     */
    public void setMessageId(String value) {
		message_id = value;
    }

    private SMPPAddress source_addr;

    /**
     * Getter for a mandatory parameter source_addr.
     * 
     * @return parameter value
     */
    public SMPPAddress getSourceAddr() {
		return source_addr;
    }

    /**
     * Setter for a mandatory parameter source_addr.
     * 
     * @param value New parameter value.
     */
    public void setSourceAddr(SMPPAddress value) {
		source_addr = value;
    }

    private SMPPTime schedule_delivery_time;

    /**
     * Getter for a mandatory parameter schedule_delivery_time.
     * 
     * @return parameter value
     */
    public SMPPTime getScheduleDeliveryTime() {
		return schedule_delivery_time;
    }

    /**
     * Setter for a mandatory parameter schedule_delivery_time.
     * 
     * @param value New parameter value.
     */
    public void setScheduleDeliveryTime(SMPPTime value) {
		schedule_delivery_time = value;
    }

    private SMPPTime validity_period;

    /**
     * Getter for a mandatory parameter validity_period.
     * 
     * @return parameter value
     */
    public SMPPTime getValidityPeriod() {
		return validity_period;
    }

    /**
     * Setter for a mandatory parameter validity_period.
     * 
     * @param value New parameter value.
     */
    public void setValidityPeriod(SMPPTime value) {
		validity_period = value;
    }

    private int registered_delivery;

    /**
     * Getter for a mandatory parameter registered_delivery.
     * 
     * @return parameter value
     */
    public int getRegisteredDelivery() {
		return registered_delivery;
    }

    /**
     * Setter for a mandatory parameter registered_delivery.
     * 
     * @param value New parameter value.
     */
    public void setRegisteredDelivery(int value) {
		registered_delivery = value;
    }

    private int sm_default_msg_id;

    /**
     * Getter for a mandatory parameter sm_default_msg_id.
     * 
     * @return parameter value
     */
    public int getSmDefaultMsgId() {
		return sm_default_msg_id;
    }

    /**
     * Setter for a mandatory parameter sm_default_msg_id.
     * 
     * @param value New parameter value.
     */
    public void setSmDefaultMsgId(int value) {
		sm_default_msg_id = value;
    }

    private byte[] short_message;

    /**
     * Getter for a mandatory parameter short_message.
     * 
     * @return parameter value
     */
    public byte[] getShortMessage() {
		return short_message;
    }

    /**
     * Setter for a mandatory parameter short_message.
     * 
     * @param value New parameter value.
     */
    public void setShortMessage(byte[] value) {
		short_message = value;
    }
}